export enum ActionTypes {
  GET_EXERCISES_REQUEST = 'GET_EXERCISES_REQUEST',
  GET_EXERCISES_SUCCESS = 'GET_EXERCISES_SUCCESS',
  GET_EXERCISES_FAIL = 'GET_EXERCISES_FAIL',

  ADD_EXERCISE_REQUEST = 'ADD_EXERCISE_REQUEST',
  ADD_EXERCISE_SUCCESS = 'ADD_EXERCISE_SUCCESS',
  ADD_EXERCISE_FAIL = 'ADD_EXERCISE_FAIL',

  GET_MUSCLE_GROUPS_REQUEST = 'GET_MUSCLE_GROUPS_REQUEST',
  GET_MUSCLE_GROUPS_SUCCESS = 'GET_MUSCLE_GROUPS_SUCCESS',
  GET_MUSCLE_GROUPS_FAIL = 'GET_MUSCLE_GROUPS_FAIL',

  GET_WEEK_SCHEDULE_REQUEST = 'GET_WEEK_SCHEDULE_REQUEST',
  GET_WEEK_SCHEDULE_SUCCESS = 'GET_WEEK_SCHEDULE_SUCCESS',
  GET_WEEK_SCHEDULE_FAIL = 'GET_WEEK_SCHEDULE_FAIL',

  UPDATE_WEEK_SCHEDULE_REQUEST = 'UPDATE_WEEK_SCHEDULE_REQUEST',
  UPDATE_WEEK_SCHEDULE_SUCCESS = 'UPDATE_WEEK_SCHEDULE_SUCCESS',
  UPDATE_WEEK_SCHEDULE_FAIL = 'UPDATE_WEEK_SCHEDULE_FAIL',
}

