export const GET_EXERCISES_REQUEST = 'GET_EXERCISES_REQUEST';
export const GET_EXERCISES_SUCCESS = 'GET_EXERCISES_SUCCESS';
export const GET_EXERCISES_FAIL = 'GET_EXERCISES_FAIL';

export const ADD_EXERCISE_REQUEST = 'ADD_EXERCISE_REQUEST';
export const ADD_EXERCISE_SUCCESS = 'ADD_EXERCISE_SUCCESS';
export const ADD_EXERCISE_FAIL = 'ADD_EXERCISE_FAIL';
